<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel?, build?)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (logicalset* | module*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalset 
  name CDATA #REQUIRED
  levels CDATA #IMPLIED  
  span CDATA #IMPLIED
  level CDATA #IMPLIED>
 <!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalsubset name CDATA #REQUIRED>
 <!ELEMENT module (component* | unit* | package* | prebuilt*)*>
 <!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED>
 <!ELEMENT component (unit* | package* | prebuilt*)*>
 <!ATTLIST component name CDATA #REQUIRED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT package EMPTY>
 <!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT prebuilt EMPTY>
 <!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>
 <!ELEMENT unitList (unitRef+)>
 <!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT unitRef EMPTY>
 <!ATTLIST unitRef unit IDREF #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED>
 <!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>
 <!ELEMENT unitListRef EMPTY>
 <!ATTLIST unitListRef unitList IDREF #REQUIRED>
 <!ELEMENT layerRef EMPTY>
 <!ATTLIST layerRef layerName CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED>
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED>
 <!ENTITY layer_real_source_path "/sf/os/mm/mmdb" >
]>
<SystemDefinition name="tb92_multimedia_daily_build" schema="1.4.0">
  <systemModel>
		<layer name="os_layer">
			<module name="multimedia_icl">
				<unit name="camerafw" unitID="sos.camerafw" bldFile="sf\os\mm\mmdb\imagingandcamerafws\camerafw\group" mrp="sf\os\mm\mmdb\imagingandcamerafws\camerafw\group\multimedia_ecam_framework.mrp"/>
			</module>
			<module name="multimedia_mmlibs">
				<unit name="mmutilitylib" unitID="sos.mmutilitylib" bldFile="sf\os\mm\mmdb\mmlibs\mmutilitylib\group" mrp="sf\os\mm\mmdb\mmlibs\mmutilitylib\group\multimedia_common.mrp"/>
				<unit name="mmfw" unitID="sos.mmfw" bldFile="sf\os\mm\mmdb\mmlibs\mmfw\group" mrp="sf\os\mm\mmlibs\mmdb\mmfw\group\multimedia_mmf.mrp"/>
			</module>
			<module name="multimedia_mmdevicefw">
				<unit name="speechrecogsupport" unitID="sos.speechrecogsupport" bldFile="sf\os\mm\mmdb\mmdevicefw\speechrecogsupport\group" mrp="sf\os\mm\mmdb\mmdevicefw\speechrecogsupport\group\multimedia_mmf_ASR.mrp"/>				
			</module>
			<module name="multimedia_devsound">
				<unit name="a3facf" unitID="sos.a3facf" bldFile="sf\os\mm\mmdb\devsound\a3facf\group" mrp="sf\os\mm\mmdb\devsound\a3facf\group\multimedia_a3f_acf.mrp"/>
				<unit name="a3fdevsound" unitID="sos.a3fdevsound" bldFile="sf\os\mm\mmdb\devsound\a3fdevsound\group" mrp="sf\os\mm\mmdb\devsound\a3fdevsound\group\multimedia_a3f_devsound.mrp"/>
				<unit name="a3fsrvstart" unitID="sos.a3fsrvstart" bldFile="sf\os\mm\mmdb\devsound\a3fsrvstart\group" mrp="sf\os\mm\mmdb\devsound\a3fsrvstart\group\multimedia_a3f_serverstart.mrp"/>
				<unit name="a3ftrace" unitID="sos.a3ftrace" bldFile="sf\os\mm\mmdb\devsound\a3ftrace\group" mrp="sf\os\mm\mmdb\devsound\a3ftrace\group\multimedia_a3f_traces.mrp"/>
				<unit name="hwdevapi" unitID="sos.hwdevapi" bldFile="sf\os\mm\mmdb\devsound\hwdevapi\group" mrp="sf\os\mm\mmdb\devsound\hwdevapi\group\multimedia_mdf_devsound_hwdev.mrp"/>	
				<unit name="devsoundapi" unitID="sos.devsoundapi" bldFile="sf\os\mm\mmdb\devsound\devsoundapi\group" mrp="sf\os\mm\mmdb\devsound\devsoundapi\group\multimedia_mdf_devsound_api.mrp"/>	
				<unit name="devsoundpluginsupport" unitID="sos.devsoundpluginsupport" bldFile="sf\os\mm\mmdb\devsound\devsoundpluginsupport\group" mrp="sf\os\mm\mmdb\devsound\devsoundpluginsupport\group\multimedia_mdf_devsound_pluginsupport.mrp"/>
			</module>
			<module name="multimedia_mmhais">
				<unit name="videohai" unitID="sos.videohai" bldFile="sf\os\mm\mmdb\mmhais\videohai\group" mrp="sf\os\mm\mmdb\mmhais\videohai\group\multimedia_videohai.mrp"/>
			</module>
			<module name="multimedia_mmplugins">
				<unit name="lib3gp" unitID="sos.lib3gp" bldFile="sf\os\mm\mmdb\mmplugins\lib3gp\group" mrp="sf\os\mm\mmdb\mmplugins\lib3gp\group\multimedia_3gplibrary.mrp"/>
			</module>
			<module name="multimedia_mmswadaptation">
				<unit name="videorenderer" unitID="sos.videorenderer" bldFile="sf\os\mm\mmdb\mmswadaptation\videorenderer\group" mrp="sf\os\mm\mmdb\mmswadaptation\videorenderer\group\multimedia_videorenderer.mrp"/>
			</module>
		</layer>		
  </systemModel>
</SystemDefinition>